version: "3.8"
services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        image: backend:test
        container_name: medusa-server
        depends_on:
            - postgres
            - redis
        environment:
            DATABASE_URL: postgres://medusa_test:medusa_test@postgres:5432/medusa_db
            POSTGRES_URL: postgres://medusa_test:medusa_test@postgres:5432/medusa_db
            REDIS_URL: redis://redis:6379
            NODE_ENV: development
            JWT_SECRET: some_jwt_secret
            COOKIE_SECRET: some_cookie_secret
            POSTGRES_DRIVER_OPTIONS: '{"connection":{"ssl":false}}'
            PORT: 9000
        ports:
            - "7001:7001"
        # command: >
        #     /bin/sh -c '
        #     echo "Executing migrations..." &&
        #     npx medusa migrations run &&
        #     echo "Creating test user..." &&
        #     npx medusa user -e test@test.com -p test &&
        #     echo "Seeding data..." &&
        #     npx medusa seed --seed-file=data/seed.json &&
        #     echo "Starting server..." &&
        #     npm run dev'
    storefront:
        build:
            context: ./storefront
            dockerfile: Dockerfile
        image: storefront:test
        container_name: medusa-storefront
        environment:
            NEXT_PUBLIC_BASE_URL: http://localhost:8000
            POSTGRES_DRIVER_OPTIONS: '{"connection":{"ssl":false}}'
        depends_on:
            - backend
            # DATABASE_URL: postgres://medusa_test:medusa_test@postgres:5432/medusa_db
        #     PORT: 8000
        # ports:
        #     - "8000:8000"
        # command: >
        #     /bin/sh -c '
        #         npm run dev'
    redis:
        image: redis
        container_name: redis
        expose:
            - 6379
    postgres:
        image: postgres:10.4
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: medusa_test
            POSTGRES_PASSWORD: medusa_test
            POSTGRES_DB: medusa_db
            PGSSLMODE: disable
        command: ["postgres", "-c", "ssl=off"]
